spring:
  application:
    name: SerenitySuites
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/serenity_suites
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
myapp:
  secret-key: 'c0388696-55b0-479c-a142-a2ae7cbe269a'

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
